import { fetchAPI } from './client';
import { Task, TaskStatus } from '../types/Task';
import { UserRole } from '../types/User';

export interface TaskFromAPI {
  _id: string;
  title: string;
  description: string;
  deadline?: string | null;
  issueId?: string | { _id: string; number?: number; title?: string } | null;
  createdBy?: string | { _id: string; username?: string; role?: UserRole } | null;
  assigneeUserId?: string | { _id: string; username?: string } | null;
  assigneeRole?: UserRole | null;
  status: TaskStatus;
  parentTaskId?: string | { _id: string; title?: string; status?: TaskStatus } | null;
  workflowStage?: number | null;
  isIssueTask?: boolean;
  isAutoGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}

const toId = (value: any): string | null => {
  if (!value) return null;
  if (typeof value === 'string') return value;
  if (typeof value === 'object' && typeof value._id === 'string') return value._id;
  return null;
};

export const transformTask = (apiTask: TaskFromAPI): Task => {
  const assigneeUsername =
    apiTask.assigneeUserId &&
    typeof apiTask.assigneeUserId === 'object' &&
    typeof (apiTask.assigneeUserId as { _id: string; username?: string }).username === 'string'
      ? (apiTask.assigneeUserId as { _id: string; username: string }).username
      : null;

  const issueInfo = apiTask.issueId && typeof apiTask.issueId === 'object'
    ? {
      id: apiTask.issueId._id,
      number: apiTask.issueId.number,
      title: apiTask.issueId.title,
    }
    : null;

  const createdByInfo = apiTask.createdBy && typeof apiTask.createdBy === 'object'
    ? {
      id: apiTask.createdBy._id,
      username: apiTask.createdBy.username,
      role: apiTask.createdBy.role,
    }
    : null;

  const parentTaskInfo = apiTask.parentTaskId && typeof apiTask.parentTaskId === 'object'
    ? {
      id: apiTask.parentTaskId._id,
      title: apiTask.parentTaskId.title,
      status: apiTask.parentTaskId.status,
    }
    : null;

  return {
    id: apiTask._id,
    title: apiTask.title,
    description: apiTask.description || '',
    deadline: apiTask.deadline ? new Date(apiTask.deadline) : null,
    issueId: toId(apiTask.issueId),
    issueInfo,
    createdBy: toId(apiTask.createdBy),
    createdByInfo,
    assigneeUserId: toId(apiTask.assigneeUserId),
    assigneeUsername,
    assigneeRole: apiTask.assigneeRole ?? null,
    status: apiTask.status,
    parentTaskId: toId(apiTask.parentTaskId) ?? null,
    parentTaskInfo,
    workflowStage: apiTask.workflowStage ?? null,
    isIssueTask: apiTask.isIssueTask ?? false,
    isAutoGenerated: apiTask.isAutoGenerated ?? false,
    createdAt: new Date(apiTask.createdAt),
    updatedAt: new Date(apiTask.updatedAt),
  };
};

export const taskAPI = {
  getTasks: async (params?: {
    issueId?: string;
    assigneeUserId?: string;
    assigneeRole?: UserRole;
    status?: TaskStatus;
    createdBy?: string;
    parentTaskId?: string;
    isIssueTask?: boolean;
    limit?: number;
  }): Promise<TaskFromAPI[]> => {
    const queryParams = new URLSearchParams();
    if (params?.issueId) queryParams.append('issueId', params.issueId);
    if (params?.assigneeUserId) queryParams.append('assigneeUserId', params.assigneeUserId);
    if (params?.assigneeRole) queryParams.append('assigneeRole', params.assigneeRole);
    if (params?.status) queryParams.append('status', params.status);
    if (params?.createdBy) queryParams.append('createdBy', params.createdBy);
    if (params?.parentTaskId) queryParams.append('parentTaskId', params.parentTaskId);
    if (params?.isIssueTask !== undefined) queryParams.append('isIssueTask', String(params.isIssueTask));
    if (params?.limit) queryParams.append('limit', String(params.limit));

    const qs = queryParams.toString();
    const endpoint = `/tasks${qs ? `?${qs}` : ''}`;

    const response = await fetchAPI<TaskFromAPI[]>(endpoint);
    if (response.success && response.data) {
      return Array.isArray(response.data) ? response.data : [];
    }
    throw new Error(response.error || 'Failed to fetch tasks');
  },

  getTaskById: async (id: string): Promise<TaskFromAPI> => {
    const response = await fetchAPI<TaskFromAPI>(`/tasks/${id}`);
    if (response.success && response.data) {
      return response.data;
    }
    throw new Error(response.error || 'Failed to fetch task');
  },

  createTask: async (payload: {
    title: string;
    description?: string;
    deadline?: string | null;
    issueId?: string | null;
    assigneeUserId?: string | null;
    assigneeRole?: UserRole | null;
    status?: TaskStatus;
    isIssueTask?: boolean;
    parentTaskId?: string | null;
  }): Promise<TaskFromAPI> => {
    const response = await fetchAPI<TaskFromAPI>('/tasks', {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    if (response.success && response.data) {
      return response.data;
    }
    throw new Error(response.error || 'Failed to create task');
  },

  updateTask: async (id: string, updates: Partial<{
    title: string;
    description: string;
    deadline: string | null;
    issueId: string | null;
    assigneeUserId: string | null;
    assigneeRole: UserRole | null;
    status: TaskStatus;
  }>): Promise<TaskFromAPI> => {
    const response = await fetchAPI<TaskFromAPI>(`/tasks/${id}`, {
      method: 'PUT',
      body: JSON.stringify(updates),
    });
    if (response.success && response.data) {
      return response.data;
    }
    throw new Error(response.error || 'Failed to update task');
  },

  deleteTask: async (id: string): Promise<void> => {
    const response = await fetchAPI<void>(`/tasks/${id}`, {
      method: 'DELETE',
    });
    if (!response.success) {
      throw new Error(response.error || 'Failed to delete task');
    }
  },
};
