import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { issueAPI, taskAPI, userAPI, transformTask } from '../../utils/api';
import type { Task, TaskStatus } from '../../types/Task';
import { UserRole } from '../../types/User';

const ROLE_LABEL: Record<string, string> = {
  author: 'Автор',
  proofreader: 'Корректор',
  illustrator: 'Иллюстратор',
  layout_designer: 'Верстальщик',
  chief_editor: 'Главный редактор',
};

const ASSIGNABLE_ROLES: UserRole[] = [
  UserRole.AUTHOR,
  UserRole.PROOFREADER,
  UserRole.ILLUSTRATOR,
  UserRole.LAYOUT_DESIGNER,
];

const STATUS_LABEL: Record<TaskStatus, string> = {
  open: 'Новая',
  in_progress: 'В работе',
  done: 'Готово',
  cancelled: 'Отменена',
};

const STATUS_ORDER: TaskStatus[] = ['open', 'in_progress', 'done', 'cancelled'];

const toDateInputValue = (d: Date | null): string => {
  if (!d) return '';
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
};

const fromDateInputValue = (value: string): string | null => {
  if (!value) return null;
  return new Date(`${value}T00:00:00.000Z`).toISOString();
};

function useBodyScrollLock(locked: boolean) {
  useEffect(() => {
    if (!locked) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prev;
    };
  }, [locked]);
}

const TaskBoard: React.FC = () => {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [users, setUsers] = useState<Array<{ id: string; username: string; role: string }>>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [formTitle, setFormTitle] = useState('');
  const [formIssueTitle, setFormIssueTitle] = useState('');
  const [formDescription, setFormDescription] = useState('');
  const [formDeadline, setFormDeadline] = useState('');
  const [formPublicationDate, setFormPublicationDate] = useState('');
  const [formIssueNumber, setFormIssueNumber] = useState('');
  const [formError, setFormError] = useState<string | null>(null);

  const [subtaskParentId, setSubtaskParentId] = useState<string | null>(null);
  const [subtaskTitle, setSubtaskTitle] = useState('');
  const [subtaskDescription, setSubtaskDescription] = useState('');
  const [subtaskDeadline, setSubtaskDeadline] = useState('');
  const [subtaskRole, setSubtaskRole] = useState<UserRole>(UserRole.AUTHOR);
  const [subtaskUserId, setSubtaskUserId] = useState('');
  const [subtaskError, setSubtaskError] = useState<string | null>(null);

  useBodyScrollLock(isCreateOpen || Boolean(subtaskParentId));

  const refresh = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [rawTasks, rawUsers] = await Promise.all([
        taskAPI.getTasks({ limit: 300 }),
        userAPI.getUsers(),
      ]);
      setTasks(rawTasks.map(transformTask));
      setUsers(rawUsers);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось загрузить задачи');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const issueTasks = useMemo(
    () => tasks.filter((task) => task.isIssueTask),
    [tasks],
  );

  const subtasksByParentId = useMemo(() => {
    const map = new Map<string, Task[]>();
    tasks
      .filter((task) => !task.isIssueTask && task.parentTaskId)
      .forEach((task) => {
        const parentId = task.parentTaskId as string;
        const list = map.get(parentId) || [];
        list.push(task);
        map.set(parentId, list);
      });
    map.forEach((list) => {
      list.sort((a, b) => {
        if (a.isAutoGenerated !== b.isAutoGenerated) {
          return a.isAutoGenerated ? 1 : -1;
        }
        return a.title.localeCompare(b.title, 'ru');
      });
    });
    return map;
  }, [tasks]);

  const usersForRole = useMemo(
    () => users.filter((u) => u.role === subtaskRole),
    [users, subtaskRole],
  );

  const toggleExpanded = (issueTaskId: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(issueTaskId)) next.delete(issueTaskId);
      else next.add(issueTaskId);
      return next;
    });
  };

  const openCreate = () => {
    setFormTitle('');
    setFormIssueTitle('');
    setFormDescription('');
    setFormDeadline('');
    setFormPublicationDate(toDateInputValue(new Date()));
    setFormIssueNumber('');
    setFormError(null);
    setIsCreateOpen(true);
  };

  const submitCreateIssue = async () => {
    setFormError(null);
    if (!formTitle.trim()) {
      setFormError('Введите название задачи выпуска');
      return;
    }
    setSaving(true);
    try {
      const number = formIssueNumber.trim() ? Number(formIssueNumber) : undefined;
      if (number !== undefined && (!Number.isFinite(number) || number < 1)) {
        setFormError('Номер выпуска должен быть положительным числом');
        setSaving(false);
        return;
      }

      await issueAPI.startIssueWorkflow({
        title: formTitle.trim(),
        issueTitle: formIssueTitle.trim() || formTitle.trim(),
        description: formDescription,
        deadline: fromDateInputValue(formDeadline),
        publicationDate: fromDateInputValue(formPublicationDate),
        number,
      });
      setIsCreateOpen(false);
      await refresh();
    } catch (err) {
      setFormError(err instanceof Error ? err.message : 'Не удалось создать выпуск');
    } finally {
      setSaving(false);
    }
  };

  const openSubtaskCreate = (parentTaskId: string) => {
    setSubtaskParentId(parentTaskId);
    setSubtaskTitle('');
    setSubtaskDescription('');
    setSubtaskDeadline('');
    setSubtaskRole(UserRole.AUTHOR);
    setSubtaskUserId('');
    setSubtaskError(null);
  };

  const submitSubtask = async () => {
    if (!subtaskParentId) return;
    setSubtaskError(null);
    if (!subtaskTitle.trim()) {
      setSubtaskError('Введите название задачи');
      return;
    }
    setSaving(true);
    try {
      await taskAPI.createTask({
        title: subtaskTitle.trim(),
        description: subtaskDescription,
        deadline: fromDateInputValue(subtaskDeadline),
        parentTaskId: subtaskParentId,
        assigneeRole: subtaskRole,
        assigneeUserId: subtaskUserId || null,
        status: 'open',
      });
      setSubtaskParentId(null);
      await refresh();
    } catch (err) {
      setSubtaskError(err instanceof Error ? err.message : 'Не удалось создать задачу');
    } finally {
      setSaving(false);
    }
  };

  const handleStatusChange = async (taskId: string, status: TaskStatus) => {
    setSaving(true);
    setError(null);
    try {
      await taskAPI.updateTask(taskId, { status });
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось обновить статус');
    } finally {
      setSaving(false);
    }
  };

  const handleDeleteIssueTask = async (taskId: string) => {
    if (!window.confirm('Удалить выпуск и все связанные задачи?')) return;
    setSaving(true);
    try {
      await taskAPI.deleteTask(taskId);
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось удалить');
    } finally {
      setSaving(false);
    }
  };

  const handleDeleteSubtask = async (task: Task) => {
    if (task.isAutoGenerated) return;
    if (!window.confirm('Удалить задачу?')) return;
    setSaving(true);
    try {
      await taskAPI.deleteTask(task.id);
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось удалить');
    } finally {
      setSaving(false);
    }
  };

  const createIssueModal = isCreateOpen ? createPortal(
    <div className="task-modal-backdrop" onClick={() => !saving && setIsCreateOpen(false)}>
      <div className="task-modal" role="dialog" aria-modal onClick={(e) => e.stopPropagation()}>
        <div className="task-modal-header">
          <h3>Новый выпуск</h3>
          <button type="button" className="task-modal-close" onClick={() => !saving && setIsCreateOpen(false)} aria-label="Закрыть">✕</button>
        </div>
        <div className="task-form">
          {formError && <div className="error-message">{formError}</div>}
          <div className="task-form-grid">
            <label className="template-select-label">
              Название задачи выпуска *
              <input className="template-select" value={formTitle} onChange={(e) => setFormTitle(e.target.value)} disabled={saving} />
            </label>
            <label className="template-select-label">
              Номер выпуска
              <input type="number" min={1} className="template-select" value={formIssueNumber} onChange={(e) => setFormIssueNumber(e.target.value)} disabled={saving} placeholder="Авто" />
            </label>
          </div>
          <label className="template-select-label">
            Название выпуска
            <input className="template-select" value={formIssueTitle} onChange={(e) => setFormIssueTitle(e.target.value)} disabled={saving} />
          </label>
          <div className="task-form-grid">
            <label className="template-select-label">
              Дата выхода
              <input type="date" className="template-select" value={formPublicationDate} onChange={(e) => setFormPublicationDate(e.target.value)} disabled={saving} />
            </label>
            <label className="template-select-label">
              Дедлайн
              <input type="date" className="template-select" value={formDeadline} onChange={(e) => setFormDeadline(e.target.value)} disabled={saving} />
            </label>
          </div>
          <label className="template-select-label">
            Описание
            <textarea className="template-select task-textarea" value={formDescription} onChange={(e) => setFormDescription(e.target.value)} disabled={saving} rows={3} />
          </label>
        </div>
        <div className="task-modal-footer">
          <button type="button" className="btn btn-auto" onClick={() => setIsCreateOpen(false)} disabled={saving}>Отмена</button>
          <button type="button" className="btn btn-auto" onClick={() => void submitCreateIssue()} disabled={saving}>
            {saving ? 'Создание...' : 'Создать'}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  ) : null;

  const subtaskModal = subtaskParentId ? createPortal(
    <div className="task-modal-backdrop" onClick={() => !saving && setSubtaskParentId(null)}>
      <div className="task-modal" role="dialog" aria-modal onClick={(e) => e.stopPropagation()}>
        <div className="task-modal-header">
          <h3>Задача для роли</h3>
          <button type="button" className="task-modal-close" onClick={() => !saving && setSubtaskParentId(null)} aria-label="Закрыть">✕</button>
        </div>
        <div className="task-form">
          {subtaskError && <div className="error-message">{subtaskError}</div>}
          <label className="template-select-label">
            Название *
            <input className="template-select" value={subtaskTitle} onChange={(e) => setSubtaskTitle(e.target.value)} disabled={saving} />
          </label>
          <div className="task-form-grid">
            <label className="template-select-label">
              Роль *
              <select className="template-select" value={subtaskRole} onChange={(e) => { setSubtaskRole(e.target.value as UserRole); setSubtaskUserId(''); }} disabled={saving}>
                {ASSIGNABLE_ROLES.map((role) => (
                  <option key={role} value={role}>{ROLE_LABEL[role] || role}</option>
                ))}
              </select>
            </label>
            <label className="template-select-label">
              Пользователь
              <select className="template-select" value={subtaskUserId} onChange={(e) => setSubtaskUserId(e.target.value)} disabled={saving}>
                <option value="">Любой с ролью</option>
                {usersForRole.map((u) => (
                  <option key={u.id} value={u.id}>{u.username}</option>
                ))}
              </select>
            </label>
          </div>
          <label className="template-select-label">
            Дедлайн
            <input type="date" className="template-select" value={subtaskDeadline} onChange={(e) => setSubtaskDeadline(e.target.value)} disabled={saving} />
          </label>
          <label className="template-select-label">
            Описание
            <textarea className="template-select task-textarea" value={subtaskDescription} onChange={(e) => setSubtaskDescription(e.target.value)} disabled={saving} rows={3} />
          </label>
        </div>
        <div className="task-modal-footer">
          <button type="button" className="btn btn-auto" onClick={() => setSubtaskParentId(null)} disabled={saving}>Отмена</button>
          <button type="button" className="btn btn-auto" onClick={() => void submitSubtask()} disabled={saving}>
            {saving ? 'Сохранение...' : 'Создать'}
          </button>
        </div>
      </div>
    </div>,
    document.body,
  ) : null;

  return (
    <div className="task-board-panel">
    <div className="task-board">
      <div className="task-board-bar">
        <div>
          <h2 className="task-board-heading">Выпуски</h2>
          <p className="task-board-sub">Создайте выпуск и добавляйте задачи для ролей. Когда автор отметит задачу «Готово», корректору появится автозадача.</p>
        </div>
        <div className="task-board-actions">
          <button type="button" className="btn btn-auto" onClick={() => void refresh()} disabled={loading || saving}>Обновить</button>
          <button type="button" className="btn btn-auto" onClick={openCreate} disabled={loading || saving}>+ Новый выпуск</button>
        </div>
      </div>

      {error && <div className="error-message">{error}</div>}

      <div className="task-board-scroll">
        {loading ? (
          <div className="empty-state"><p className="empty-state-title">Загрузка...</p></div>
        ) : issueTasks.length === 0 ? (
          <div className="empty-state">
            <p className="empty-state-title">Нет выпусков</p>
            <p className="empty-state-text">Создайте выпуск и назначьте задачи авторам и другим ролям.</p>
          </div>
        ) : (
          <div className="issue-cards-list">
            {issueTasks.map((issueTask) => {
              const subtasks = subtasksByParentId.get(issueTask.id) || [];
              const manualSubtasks = subtasks.filter((t) => !t.isAutoGenerated);
              const autoSubtasks = subtasks.filter((t) => t.isAutoGenerated);
              const doneCount = subtasks.filter((t) => t.status === 'done').length;
              const expanded = expandedIds.has(issueTask.id);

              return (
                <article className="issue-task-card" key={issueTask.id}>
                  <div className="issue-task-card-header">
                    <div className="issue-task-card-meta">
                      {issueTask.issueInfo && (
                        <span className="issue-tasks-badge">
                          Выпуск №{issueTask.issueInfo.number}
                          {issueTask.issueInfo.title ? ` · ${issueTask.issueInfo.title}` : ''}
                        </span>
                      )}
                      <h3 className="issue-task-card-title">{issueTask.title}</h3>
                      {issueTask.description && <p className="issue-task-card-desc">{issueTask.description}</p>}
                      <p className="issue-task-progress">
                        Задач: {doneCount}/{subtasks.length} выполнено
                        {autoSubtasks.length > 0 ? ` · авто: ${autoSubtasks.length}` : ''}
                      </p>
                    </div>
                    <div className="issue-task-card-actions">
                      <button type="button" className="btn btn-small btn-auto" onClick={() => openSubtaskCreate(issueTask.id)} disabled={saving}>
                        + Задача
                      </button>
                      <button type="button" className="btn btn-small btn-auto" onClick={() => toggleExpanded(issueTask.id)} disabled={saving}>
                        {expanded ? 'Свернуть' : `Ручные (${manualSubtasks.length})`}
                      </button>
                    </div>
                  </div>

                  {autoSubtasks.length > 0 && (
                    <div className="issue-task-auto-strip">
                      <p className="issue-task-auto-strip-title">Автоматические задачи</p>
                      {autoSubtasks.map((subtask) => (
                        <div className="issue-task-auto-chip" key={subtask.id}>
                          <span className="issue-task-auto-chip-title" title={subtask.title}>
                            {subtask.assigneeRole ? ROLE_LABEL[subtask.assigneeRole] : '—'}: {subtask.title}
                          </span>
                          <span className={`task-status task-status-${subtask.status}`}>{STATUS_LABEL[subtask.status]}</span>
                        </div>
                      ))}
                    </div>
                  )}

                  {expanded && (
                    <div className="issue-task-subtasks">
                      {manualSubtasks.length === 0 ? (
                        <p className="issue-task-empty-hint">Нет ручных задач — нажмите «+ Задача». После «Готово» у автора появится задача корректору.</p>
                      ) : (
                        <div className="subtask-table">
                          <div className="subtask-table-head">
                            <span>Роль</span>
                            <span>Задача</span>
                            <span>Статус</span>
                            <span />
                          </div>
                          {manualSubtasks.map((subtask) => (
                            <div className="subtask-table-row" key={subtask.id}>
                              <span className="subtask-row-role">
                                {subtask.assigneeRole ? ROLE_LABEL[subtask.assigneeRole] : '—'}
                                {subtask.isAutoGenerated && <span className="task-pill task-pill-auto">авто</span>}
                              </span>
                              <span className="subtask-row-title" title={subtask.title}>{subtask.title}</span>
                              <span className={`task-status task-status-${subtask.status}`}>{STATUS_LABEL[subtask.status]}</span>
                              <span className="subtask-row-actions">
                                <select
                                  className="template-select subtask-status-select"
                                  value={subtask.status}
                                  onChange={(e) => void handleStatusChange(subtask.id, e.target.value as TaskStatus)}
                                  disabled={saving}
                                >
                                  {STATUS_ORDER.map((status) => (
                                    <option key={status} value={status}>{STATUS_LABEL[status]}</option>
                                  ))}
                                </select>
                                {!subtask.isAutoGenerated && (
                                  <button type="button" className="btn btn-small task-danger" onClick={() => void handleDeleteSubtask(subtask)} disabled={saving}>✕</button>
                                )}
                              </span>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}

                  <footer className="issue-task-card-footer">
                    <select
                      className="template-select issue-task-status-select"
                      value={issueTask.status}
                      onChange={(e) => void handleStatusChange(issueTask.id, e.target.value as TaskStatus)}
                      disabled={saving}
                    >
                      {STATUS_ORDER.map((status) => (
                        <option key={status} value={status}>{STATUS_LABEL[status]}</option>
                      ))}
                    </select>
                    <button type="button" className="btn btn-small task-danger" onClick={() => void handleDeleteIssueTask(issueTask.id)} disabled={saving}>
                      Удалить выпуск
                    </button>
                  </footer>
                </article>
              );
            })}
          </div>
        )}
      </div>

      {createIssueModal}
      {subtaskModal}
    </div>
    </div>
  );
};

export default TaskBoard;
