const Task = require('../models/Task');
const Article = require('../models/Article');
const Issue = require('../models/Issue');

const findActiveIssueTask = async (issueId) => {
  if (!issueId) return null;
  return Task.findOne({
    issueId,
    isIssueTask: true,
    status: { $nin: ['done', 'cancelled'] },
  });
};

const findIssueTask = async (issueId) => {
  if (!issueId) return null;
  return Task.findOne({ issueId, isIssueTask: true }).sort({ updatedAt: -1 });
};

const findOpenAutoTask = async (issueId, role) => {
  return Task.findOne({
    issueId,
    assigneeRole: role,
    isAutoGenerated: true,
    status: { $nin: ['done', 'cancelled'] },
  });
};

const findAuthorTaskForArticle = async (issueId, articleId) => {
  if (!articleId) return null;
  return Task.findOne({
    issueId,
    articleId,
    assigneeRole: 'author',
    isAutoGenerated: false,
    isIssueTask: false,
  });
};

const findActiveAuthorTaskForArticle = async (issueId, articleId) => {
  if (!articleId) return null;
  return Task.findOne({
    issueId,
    articleId,
    assigneeRole: 'author',
    isAutoGenerated: false,
    isIssueTask: false,
    status: { $nin: ['done', 'cancelled'] },
  }).sort({ updatedAt: -1 });
};

const findActiveProofreaderTaskForArticle = async (issueId, articleId) => {
  if (!articleId) return null;
  return Task.findOne({
    issueId,
    articleId,
    assigneeRole: 'proofreader',
    isAutoGenerated: true,
    status: { $nin: ['done', 'cancelled'] },
  }).sort({ updatedAt: -1 });
};

const articleScopeFilter = (authorTask) => {
  if (authorTask?.articleId) {
    return { articleId: authorTask.articleId };
  }
  return { parentTaskId: authorTask._id };
};

/**
 * Links article to issue from author's open manual task.
 */
async function ensureArticleIssueId(article) {
  if (article.issueId) return article;

  const authorId = article.authorId?.toString();
  if (!authorId) return article;

  const openAuthorTasks = await Task.find({
    assigneeRole: 'author',
    issueId: { $ne: null },
    parentTaskId: { $ne: null },
    isIssueTask: false,
    isAutoGenerated: false,
    status: { $nin: ['done', 'cancelled'] },
    $or: [
      { assigneeUserId: authorId },
      { assigneeUserId: null },
    ],
  }).sort({ updatedAt: -1 });

  const assignedTask = openAuthorTasks.find((t) => t.assigneeUserId?.toString() === authorId);
  const task = assignedTask || openAuthorTasks[0];

  if (task?.issueId) {
    article.issueId = task.issueId;
    await article.save();
  }

  return article;
}

/**
 * When an author's manual task is marked done, creates a proofreader auto-task.
 */
async function onAuthorTaskMarkedDone(authorTask, userId) {
  try {
    if (!authorTask || authorTask.isIssueTask || authorTask.isAutoGenerated) return;
    if (authorTask.assigneeRole !== 'author') return;
    if (!authorTask.issueId) return;

    const issueId = authorTask.issueId.toString();
    const issueTask = await findActiveIssueTask(issueId);
    if (!issueTask) return;

    const scope = articleScopeFilter(authorTask);
    const existing = await Task.findOne({
      issueId,
      assigneeRole: 'proofreader',
      isAutoGenerated: true,
      status: { $nin: ['done', 'cancelled'] },
      ...scope,
    });
    if (existing) {
      if (existing.status === 'open') {
        await Task.findByIdAndUpdate(existing._id, { status: 'in_progress' });
      }
      return;
    }

    const article = authorTask.articleId
      ? await Article.findById(authorTask.articleId).select('title')
      : null;
    const articleTitle = article?.title || authorTask.title.replace(/^Написать:\s*/, '');

    await Task.create({
      title: `Проверить: ${articleTitle}`,
      description: `Автор завершил задачу «${authorTask.title}». Проверьте текст статьи и оформите замечания при необходимости.`,
      issueId,
      parentTaskId: issueTask._id,
      articleId: authorTask.articleId || null,
      assigneeRole: 'proofreader',
      assigneeUserId: authorTask.assignedProofreaderId || null,
      createdBy: userId,
      status: 'in_progress',
      isAutoGenerated: true,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] onAuthorTaskMarkedDone error:', err.message);
  }
}

/**
 * When a proofreader auto-task is marked done, creates an illustrator auto-task.
 */
async function onProofreaderTaskMarkedDone(proofreaderTask, userId) {
  try {
    if (!proofreaderTask?.isAutoGenerated || proofreaderTask.assigneeRole !== 'proofreader') return;
    if (!proofreaderTask.issueId) return;

    const issueId = proofreaderTask.issueId.toString();
    const issueTask = await findActiveIssueTask(issueId);
    if (!issueTask) return;

    const authorTask = proofreaderTask.articleId
      ? await findAuthorTaskForArticle(issueId, proofreaderTask.articleId)
      : null;
    const illustratorId = authorTask?.assignedIllustratorId || null;
    if (!illustratorId) return;

    const scope = proofreaderTask.articleId
      ? { articleId: proofreaderTask.articleId }
      : { parentTaskId: proofreaderTask.parentTaskId };

    const existing = await Task.findOne({
      issueId,
      assigneeRole: 'illustrator',
      isAutoGenerated: true,
      status: { $nin: ['done', 'cancelled'] },
      ...scope,
    });
    if (existing) {
      if (existing.status === 'open') {
        await Task.findByIdAndUpdate(existing._id, { status: 'in_progress' });
      }
      return;
    }

    const article = proofreaderTask.articleId
      ? await Article.findById(proofreaderTask.articleId).select('title')
      : null;
    const articleTitle = article?.title || proofreaderTask.title.replace(/^Проверить:\s*/, '');

    await Task.create({
      title: `Иллюстрация: ${articleTitle}`,
      description: `Корректор завершил проверку статьи «${articleTitle}». Подготовьте иллюстрацию к материалу.`,
      issueId,
      parentTaskId: issueTask._id,
      articleId: proofreaderTask.articleId || null,
      assigneeRole: 'illustrator',
      assigneeUserId: illustratorId,
      createdBy: userId,
      status: 'in_progress',
      isAutoGenerated: true,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] onProofreaderTaskMarkedDone error:', err.message);
  }
}

/**
 * When an illustrator auto-task is marked done, checks if the whole issue is ready for layout.
 */
async function onIllustratorTaskMarkedDone(illustratorTask, userId) {
  try {
    if (illustratorTask?.assigneeRole !== 'illustrator') return;
    if (!illustratorTask.issueId) return;
    await checkAndCreateLayoutTask(illustratorTask.issueId.toString(), userId);
  } catch (err) {
    console.error('[taskService] onIllustratorTaskMarkedDone error:', err.message);
  }
}

/**
 * Author submitted article for proofreading: complete author task and assign proofreader.
 */
async function onArticleSubmittedForReview(article, userId) {
  try {
    const articleDoc = await ensureArticleIssueId(article);
    if (!articleDoc.issueId) return;

    const issueId = articleDoc.issueId.toString();
    let authorTask = await findActiveAuthorTaskForArticle(issueId, articleDoc._id);

    if (!authorTask) {
      authorTask = await Task.findOne({
        issueId,
        assigneeRole: 'author',
        assigneeUserId: articleDoc.authorId,
        isAutoGenerated: false,
        isIssueTask: false,
        status: { $nin: ['done', 'cancelled'] },
      }).sort({ updatedAt: -1 });
    }

    if (!authorTask) return;

    if (authorTask.status !== 'done') {
      authorTask.status = 'done';
      await authorTask.save();
    }

    await onAuthorTaskMarkedDone(authorTask, userId);
  } catch (err) {
    console.error('[taskService] onArticleSubmittedForReview error:', err.message);
  }
}

/**
 * Proofreader approved article: complete proofreader task and assign illustrator.
 */
async function onArticleApprovedByProofreader(article, userId) {
  try {
    const articleDoc = article.issueId ? article : await ensureArticleIssueId(article);
    if (!articleDoc.issueId) return;

    const issueId = articleDoc.issueId.toString();
    const proofreaderTask = await findActiveProofreaderTaskForArticle(issueId, articleDoc._id);
    if (!proofreaderTask) return;

    if (proofreaderTask.status !== 'done') {
      proofreaderTask.status = 'done';
      await proofreaderTask.save();
      await onProofreaderTaskMarkedDone(proofreaderTask, userId);
    }
  } catch (err) {
    console.error('[taskService] onArticleApprovedByProofreader error:', err.message);
  }
}

/**
 * Proofreader returned article to author: cancel proofreader task and create revision task.
 */
async function onArticleReturnedForRevision(article, revisionNote, userId) {
  try {
    const articleDoc = await ensureArticleIssueId(article);
    if (!articleDoc.issueId) return;

    const issueId = articleDoc.issueId.toString();
    const issueTask = await findActiveIssueTask(issueId);
    if (!issueTask) return;

    const proofreaderTask = await findActiveProofreaderTaskForArticle(issueId, articleDoc._id);
    if (proofreaderTask) {
      proofreaderTask.status = 'cancelled';
      await proofreaderTask.save();
    }

    const priorAuthorTask = await Task.findOne({
      issueId,
      articleId: articleDoc._id,
      assigneeRole: 'author',
      isAutoGenerated: false,
      isIssueTask: false,
    }).sort({ updatedAt: -1 });

    const articleTitle = articleDoc.title || 'Статья';

    await Task.create({
      title: `Доработать: ${articleTitle}`,
      description: revisionNote,
      issueId,
      parentTaskId: issueTask._id,
      articleId: articleDoc._id,
      assigneeRole: 'author',
      assigneeUserId: articleDoc.authorId,
      assignedProofreaderId: priorAuthorTask?.assignedProofreaderId || null,
      assignedIllustratorId: priorAuthorTask?.assignedIllustratorId || null,
      createdBy: userId,
      status: 'in_progress',
      isAutoGenerated: false,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] onArticleReturnedForRevision error:', err.message);
  }
}

/**
 * When all author/proofreader/illustrator tasks for every article are done,
 * creates a layout designer task.
 */
async function checkAndCreateLayoutTask(issueId, systemUserId) {
  try {
    if (!issueId) return;

    const issueIdStr = issueId.toString();
    const issueTask = await findIssueTask(issueIdStr);
    if (!issueTask) return;

    const existing = await findOpenAutoTask(issueIdStr, 'layout_designer');
    if (existing) return;

    const authorTasks = await Task.find({
      issueId: issueIdStr,
      parentTaskId: issueTask._id,
      assigneeRole: 'author',
      isAutoGenerated: false,
      isIssueTask: false,
      status: { $ne: 'cancelled' },
    });

    if (authorTasks.length === 0) return;

    for (const authorTask of authorTasks) {
      if (authorTask.status !== 'done') return;

      const scope = articleScopeFilter(authorTask);

      const proofreaderDone = await Task.findOne({
        issueId: issueIdStr,
        assigneeRole: 'proofreader',
        isAutoGenerated: true,
        status: 'done',
        ...scope,
      });
      if (!proofreaderDone) return;

      const illustratorDone = await Task.findOne({
        issueId: issueIdStr,
        assigneeRole: 'illustrator',
        status: 'done',
        ...scope,
      });
      if (!illustratorDone) return;
    }

    const issue = await Issue.findById(issueIdStr)
      .populate('templateId', 'name')
      .select('number title pageCount layoutNotes assignedLayoutDesignerId templateId publicationDate');

    const issueLabel = issue
      ? `Выпуск №${issue.number}${issue.title ? ` — ${issue.title}` : ''}`
      : issueTask.title;

    const descriptionParts = [
      'Все материалы выпуска готовы. Сверьтесь с конфигурацией и приступите к вёрстке.',
    ];

    if (issue?.pageCount) {
      descriptionParts.push(`Страниц: ${issue.pageCount}.`);
    }

    if (issue?.templateId?.name) {
      descriptionParts.push(`Шаблон: ${issue.templateId.name}.`);
    }

    if (issue?.publicationDate) {
      descriptionParts.push(
        `Дата выхода: ${new Date(issue.publicationDate).toLocaleDateString('ru-RU')}.`,
      );
    }

    if (issueTask.description?.trim()) {
      descriptionParts.push(`\nОписание выпуска:\n${issueTask.description.trim()}`);
    }

    if (issue?.layoutNotes?.trim()) {
      descriptionParts.push(`\nЗаметки для верстальщика:\n${issue.layoutNotes.trim()}`);
    }

    await Task.create({
      title: `Конфигурация выпуска: ${issueLabel}`,
      description: descriptionParts.join('\n'),
      issueId: issueIdStr,
      parentTaskId: issueTask._id,
      assigneeRole: 'layout_designer',
      assigneeUserId: issue?.assignedLayoutDesignerId || null,
      createdBy: systemUserId,
      status: 'in_progress',
      isAutoGenerated: true,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] checkAndCreateLayoutTask error:', err.message);
  }
}

/**
 * Layout designer submitted issue for chief editor review.
 */
async function onLayoutSubmittedForReview(issueId, userId) {
  try {
    if (!issueId) return;

    const issueIdStr = issueId.toString();
    const issueTask = await findIssueTask(issueIdStr);

    const layoutTasks = await Task.find({
      issueId: issueIdStr,
      assigneeRole: 'layout_designer',
      status: { $nin: ['done', 'cancelled'] },
    });

    await Promise.all(
      layoutTasks.map(async (task) => {
        task.status = 'done';
        await task.save();
      }),
    );

    const existingReviewTask = await Task.findOne({
      issueId: issueIdStr,
      assigneeRole: 'chief_editor',
      isAutoGenerated: true,
      status: { $nin: ['done', 'cancelled'] },
      title: { $regex: /^Проверить макет:/ },
    });
    if (existingReviewTask) return;

    const issue = await Issue.findById(issueIdStr).select('number title');
    const issueLabel = issue
      ? `Выпуск №${issue.number}${issue.title ? ` — ${issue.title}` : ''}`
      : 'Выпуск';

    await Task.create({
      title: `Проверить макет: ${issueLabel}`,
      description: 'Верстальщик отправил макет на проверку. Откройте раздел «Проверка макетов».',
      issueId: issueIdStr,
      parentTaskId: issueTask?._id ?? null,
      assigneeRole: 'chief_editor',
      assigneeUserId: null,
      createdBy: userId,
      status: 'in_progress',
      isAutoGenerated: true,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] onLayoutSubmittedForReview error:', err.message);
  }
}

module.exports = {
  onAuthorTaskMarkedDone,
  onProofreaderTaskMarkedDone,
  onIllustratorTaskMarkedDone,
  checkAndCreateLayoutTask,
  ensureArticleIssueId,
  onArticleSubmittedForReview,
  onArticleApprovedByProofreader,
  onArticleReturnedForRevision,
  onLayoutSubmittedForReview,
};
