const Task = require('../models/Task');
const Article = require('../models/Article');
const Illustration = require('../models/Illustration');
const Issue = require('../models/Issue');

const findActiveIssueTask = async (issueId) => {
  if (!issueId) return null;
  return Task.findOne({
    issueId,
    isIssueTask: true,
    status: { $nin: ['done', 'cancelled'] },
  });
};

const findOpenAutoTask = async (issueId, role) => {
  return Task.findOne({
    issueId,
    assigneeRole: role,
    isAutoGenerated: true,
    status: { $nin: ['done', 'cancelled'] },
  });
};

/**
 * Links article to issue from author's open manual task (chief editor does not set issueId in author UI yet).
 */
async function ensureArticleIssueId(article) {
  if (article.issueId) return article;

  const authorId = article.authorId?.toString();
  if (!authorId) return article;

  const openAuthorTasks = await Task.find({
    assigneeRole: 'author',
    issueId: { $ne: null },
    parentTaskId: { $ne: null },
    isIssueTask: false,
    isAutoGenerated: false,
    status: { $nin: ['done', 'cancelled'] },
    $or: [
      { assigneeUserId: authorId },
      { assigneeUserId: null },
    ],
  }).sort({ updatedAt: -1 });

  const assignedTask = openAuthorTasks.find((t) => t.assigneeUserId?.toString() === authorId);
  const task = assignedTask || openAuthorTasks[0];

  if (task?.issueId) {
    article.issueId = task.issueId;
    await article.save();
  }

  return article;
}

/**
 * When an author's manual task is marked done, creates a proofreader auto-task for the issue.
 */
async function onAuthorTaskMarkedDone(authorTask, userId) {
  try {
    if (!authorTask || authorTask.isIssueTask || authorTask.isAutoGenerated) return;
    if (authorTask.assigneeRole !== 'author') return;
    if (!authorTask.issueId) return;

    const issueId = authorTask.issueId.toString();
    const issueTask = await findActiveIssueTask(issueId);
    if (!issueTask) return;

    const existing = await findOpenAutoTask(issueId, 'proofreader');
    if (existing) {
      if (existing.status === 'open') {
        await Task.findByIdAndUpdate(existing._id, { status: 'in_progress' });
      }
      return;
    }

    const issue = await Issue.findById(issueId).select('number title');
    const issueLabel = issue
      ? `Выпуск №${issue.number}${issue.title ? ` — ${issue.title}` : ''}`
      : issueTask.title;

    await Task.create({
      title: `Проверьте статью: ${issueLabel}`,
      description: `Автор завершил задачу «${authorTask.title}». Проверьте текст статьи и оформите замечания при необходимости.`,
      issueId,
      parentTaskId: issueTask._id,
      assigneeRole: 'proofreader',
      createdBy: userId,
      status: 'in_progress',
      isAutoGenerated: true,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] onAuthorTaskMarkedDone error:', err.message);
  }
}

/**
 * When all issue articles are approved and illustrated, creates a layout designer task.
 */
async function checkAndCreateLayoutTask(issueId, systemUserId) {
  try {
    if (!issueId) return;

    const issueIdStr = issueId.toString();
    const articles = await Article.find({ issueId: issueIdStr });
    if (articles.length === 0) return;

    const allApproved = articles.every((a) => a.status === 'approved');
    if (!allApproved) return;

    const articleIds = articles.map((a) => a._id);
    const illustrations = await Illustration.find({ articleId: { $in: articleIds } });
    const coveredIds = new Set(illustrations.map((i) => i.articleId.toString()));
    const allHaveIllustration = articleIds.every((id) => coveredIds.has(id.toString()));
    if (!allHaveIllustration) return;

    const issueTask = await findActiveIssueTask(issueIdStr);
    if (!issueTask) return;

    const existing = await findOpenAutoTask(issueIdStr, 'layout_designer');
    if (existing) return;

    const issue = await Issue.findById(issueIdStr).select('number title');
    const issueLabel = issue
      ? `Выпуск №${issue.number}${issue.title ? ` — ${issue.title}` : ''}`
      : issueTask.title;

    await Task.create({
      title: `Сформировать выпуск: ${issueLabel}`,
      description: 'Все материалы выпуска готовы: статьи утверждены, иллюстрации добавлены.',
      issueId: issueIdStr,
      parentTaskId: issueTask._id,
      assigneeRole: 'layout_designer',
      createdBy: systemUserId,
      status: 'in_progress',
      isAutoGenerated: true,
      isIssueTask: false,
      workflowStage: null,
    });
  } catch (err) {
    console.error('[taskService] checkAndCreateLayoutTask error:', err.message);
  }
}

module.exports = {
  onAuthorTaskMarkedDone,
  checkAndCreateLayoutTask,
  ensureArticleIssueId,
};
