import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { taskAPI, transformTask } from '../../utils/api';
import type { Task, TaskStatus } from '../../types/Task';

const STATUS_LABEL: Record<TaskStatus, string> = {
  open: 'Новая',
  in_progress: 'В работе',
  done: 'Готово',
  cancelled: 'Отменена',
};

const STATUS_ORDER: TaskStatus[] = ['open', 'in_progress', 'done', 'cancelled'];

const toDateDisplay = (d: Date | null): string => {
  if (!d) return '';
  try { return d.toLocaleDateString('ru-RU'); } catch { return ''; }
};

const isOverdue = (d: Date | null): boolean => {
  if (!d) return false;
  return d < new Date();
};

interface IssueTaskGroup {
  issueId: string;
  label: string;
  parentTitle: string | null;
  tasks: Task[];
}

interface MyTasksPageProps {
  onTasksLoaded?: (count: number) => void;
}

const MyTasksPage: React.FC<MyTasksPageProps> = ({ onTasksLoaded }) => {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [savingId, setSavingId] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const raw = await taskAPI.getTasks({ limit: 200 });
      const loaded = raw
        .map(transformTask)
        .filter((task) => !task.isIssueTask);
      setTasks(loaded);
      onTasksLoaded?.(loaded.filter(t => t.status !== 'done' && t.status !== 'cancelled').length);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось загрузить задачи');
    } finally {
      setLoading(false);
    }
  }, [onTasksLoaded]);

  useEffect(() => { void refresh(); }, [refresh]);

  useEffect(() => {
    const interval = setInterval(() => { void refresh(); }, 30_000);
    return () => clearInterval(interval);
  }, [refresh]);

  const onStatusChange = async (taskId: string, next: TaskStatus) => {
    setSavingId(taskId);
    setError(null);
    try {
      await taskAPI.updateTask(taskId, { status: next });
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Не удалось обновить задачу');
    } finally {
      setSavingId(null);
    }
  };

  const { issueGroups, orphanTasks } = useMemo(() => {
    const map = new Map<string, IssueTaskGroup>();
    const orphans: Task[] = [];

    tasks.forEach((task) => {
      if (!task.issueId) {
        orphans.push(task);
        return;
      }

      const key = task.issueId;
      if (!map.has(key)) {
        const num = task.issueInfo?.number;
        const issueTitle = task.issueInfo?.title;
        const label = num !== undefined
          ? `Выпуск №${num}${issueTitle ? ` · ${issueTitle}` : ''}`
          : (issueTitle || 'Выпуск');
        map.set(key, {
          issueId: key,
          label,
          parentTitle: task.parentTaskInfo?.title ?? null,
          tasks: [],
        });
      }
      map.get(key)!.tasks.push(task);
    });

    const groups = Array.from(map.values()).sort((a, b) => a.label.localeCompare(b.label, 'ru'));
    groups.forEach((g) => {
      g.tasks.sort((a, b) => {
        const order = STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status);
        if (order !== 0) return order;
        return a.title.localeCompare(b.title, 'ru');
      });
    });

    return { issueGroups: groups, orphanTasks: orphans };
  }, [tasks]);

  if (loading) {
    return (
      <div className="my-tasks-page">
        <div className="empty-state"><p className="empty-state-title">Загрузка...</p></div>
      </div>
    );
  }

  const renderTaskCard = (t: Task) => (
    <div
      key={t.id}
      className={`task-card task-card--issue-linked ${isOverdue(t.deadline) && t.status !== 'done' && t.status !== 'cancelled' ? 'task-card-overdue' : ''}`}
    >
      <div className="task-card-top">
        <div className="task-card-title">{t.title}</div>
        {t.isAutoGenerated && <span className="task-pill task-pill-auto">Авто</span>}
      </div>
      {t.description && <div className="task-card-desc">{t.description}</div>}
      {t.deadline && (
        <div className={`task-card-deadline ${isOverdue(t.deadline) && t.status !== 'done' ? 'overdue' : ''}`}>
          Дедлайн: {toDateDisplay(t.deadline)}
          {isOverdue(t.deadline) && t.status !== 'done' && t.status !== 'cancelled' && (
            <span className="overdue-label"> · просрочено</span>
          )}
        </div>
      )}
      <div className="task-card-footer">
        <span className={`task-status task-status-${t.status}`}>{STATUS_LABEL[t.status]}</span>
        <select
          className="task-card-status-select"
          value={t.status}
          onChange={e => void onStatusChange(t.id, e.target.value as TaskStatus)}
          disabled={savingId === t.id}
        >
          {STATUS_ORDER.map(s => (
            <option key={s} value={s}>{STATUS_LABEL[s]}</option>
          ))}
        </select>
      </div>
    </div>
  );

  return (
    <div className="my-tasks-page">
      {error && <div className="error-message">{error}</div>}

      {tasks.length === 0 ? (
        <div className="empty-state">
          <p className="empty-state-title">Нет задач</p>
          <p className="empty-state-text">Когда главный редактор назначит задачу по выпуску, она появится здесь.</p>
        </div>
      ) : (
        <div className="my-tasks-groups">
          {issueGroups.map((group) => (
            <section className="issue-tasks-group" key={group.issueId}>
              <header className="issue-tasks-group-header">
                <div className="issue-tasks-group-title">
                  <span className="issue-tasks-badge">{group.label}</span>
                  {group.parentTitle && (
                    <span className="issue-tasks-parent">{group.parentTitle}</span>
                  )}
                </div>
                <span className="issue-tasks-count">{group.tasks.length} задач</span>
              </header>
              <div className="issue-tasks-grid">
                {group.tasks.map(renderTaskCard)}
              </div>
            </section>
          ))}

          {orphanTasks.length > 0 && (
            <section className="issue-tasks-group issue-tasks-group--orphan">
              <header className="issue-tasks-group-header">
                <span className="issue-tasks-badge issue-tasks-badge--muted">Без выпуска</span>
              </header>
              <div className="issue-tasks-grid">
                {orphanTasks.map(renderTaskCard)}
              </div>
            </section>
          )}
        </div>
      )}
    </div>
  );
};

export default MyTasksPage;
