const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Title is required'],
    trim: true,
  },
  description: {
    type: String,
    default: '',
  },
  deadline: {
    type: Date,
    default: null,
  },
  issueId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Issue',
    default: null,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'CreatedBy is required'],
  },
  assigneeUserId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
  },
  assigneeRole: {
    type: String,
    enum: ['author', 'proofreader', 'illustrator', 'layout_designer', 'chief_editor'],
    default: null,
  },
  status: {
    type: String,
    enum: ['open', 'in_progress', 'done', 'cancelled'],
    default: 'open',
  },
  parentTaskId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Task',
    default: null,
  },
  workflowStage: {
    type: Number,
    min: 1,
    max: 5,
    default: null,
  },
  isIssueTask: {
    type: Boolean,
    default: false,
  },
  isAutoGenerated: {
    type: Boolean,
    default: false,
  },
}, {
  timestamps: true,
});

taskSchema.index({ issueId: 1, status: 1 });
taskSchema.index({ assigneeUserId: 1, status: 1 });
taskSchema.index({ assigneeRole: 1, status: 1 });
taskSchema.index({ status: 1, deadline: 1 });
taskSchema.index({ createdBy: 1, status: 1 });
taskSchema.index({ parentTaskId: 1, workflowStage: 1 });

taskSchema.pre('validate', function validateAssignment(next) {
  // Issue_Tasks are not assigned to anyone — they are parent tasks managed by chief_editor
  if (this.isIssueTask) {
    return next();
  }
  const hasUser = !!this.assigneeUserId;
  const hasRole = !!this.assigneeRole;
  if (!hasUser && !hasRole) {
    this.invalidate('assigneeUserId', 'Either assigneeUserId or assigneeRole is required');
    this.invalidate('assigneeRole', 'Either assigneeUserId or assigneeRole is required');
  }
  next();
});

taskSchema.methods.toClientObject = function toClientObject() {
  return {
    id: this._id.toString(),
    title: this.title,
    description: this.description,
    deadline: this.deadline,
    issueId: this.issueId ? this.issueId.toString() : null,
    createdBy: this.createdBy ? this.createdBy.toString() : null,
    assigneeUserId: this.assigneeUserId ? this.assigneeUserId.toString() : null,
    assigneeRole: this.assigneeRole,
    status: this.status,
    parentTaskId: this.parentTaskId ? this.parentTaskId.toString() : null,
    workflowStage: this.workflowStage,
    isIssueTask: this.isIssueTask,
    isAutoGenerated: this.isAutoGenerated,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt,
  };
};

const Task = mongoose.model('Task', taskSchema);

module.exports = Task;

