import { UserRole } from './User';

export type TaskStatus = 'open' | 'in_progress' | 'done' | 'cancelled';

export interface Task {
  id: string;
  title: string;
  description: string;
  deadline: Date | null;
  issueId: string | null;
  issueInfo: {
    id: string;
    number?: number;
    title?: string;
  } | null;
  createdBy: string | null;
  createdByInfo: {
    id: string;
    username?: string;
    role?: UserRole;
  } | null;
  assigneeUserId: string | null;
  assigneeUsername: string | null;
  assigneeRole: UserRole | null;
  status: TaskStatus;
  parentTaskId: string | null;
  parentTaskInfo: {
    id: string;
    title?: string;
    status?: TaskStatus;
  } | null;
  workflowStage: number | null;
  isIssueTask: boolean;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}
